version: "3"
services:
  ganache:
    image: devchetal/dock_eth_gan_3:v1
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
  dapp:
    image: devchetal/dock_eth_gan:v2
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - ganache

  react:
    image: devchetal/dock_eth_gan_2:v1
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - dapp

  mongodb:
    image: mongo:latest # Use the official MongoDB image
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db # Persist MongoDB data

volumes:
  mongodb-data:
    driver: local